### PR TITLE
Fix percent encoding

### LINKED ISSUE #9: Parsing issue with bit.ly when long url contains "#"
ex: Long Url: ```google.com/asd#123```
Output :
```{"status_code":200,"status_txt":"OK","data":{"url":"http://bit.ly/2nYsQDH","hash":"2nYsQDH","global_hash":"ipdYoe","long_url":"http://google.com/asd","new_hash":0}}```

### PR DESCRIPTION
**Pull request by arshubham**
Fixes #9

### CODE REVIEW

**Comment by iddm** [comment]
I am far away from a chance of testing this. Did you test this, everything works as expected?

**Comment by arshubham** [comment]
Yeah I tested it using git as a source in cargo  and it works.

**Comment by iddm** [comment]
@arshubham Thanks very much for your contribution!

**Comment by iddm** [comment]
Interesting problem with the  `hmm.rs` provider... Let me check what is the problem with it.

**Comment by arshubham** [comment]
I don't think its related as I am getting Decode error on even the crate.io version on my application

**Comment by iddm** [comment]
@arshubham Yes, I don't think it is related too. Just wanna fix it anyway if it is possible.

**Comment by arshubham** [comment]
Just Debugged it using httpie the post request is returning correct result. I will try to debug more

**Comment by iddm** [comment]
@arshubham Yes, I am debugging that too. However, I found that the format has changed a little bit - earlier it accepted the url-encoded post data, now the service uses `json` with the `json-formed` data. I have changed it accordingly but this does not help too. Looking further.

Even `curl` works:
```bash
curl -H "Content-Type: application/json" -X POST -d '{"url":"http://ya.ru"}' http://hmm.rs/x/shorten
```

**Comment by iddm** [comment]
@arshubham No, this will not work. The problem is one I was afraid of: author changed the security mechanisms:

```
Request shortening via provider: hmm.rs
Response: Ok(Response { url: "http://hmm.rs/x/shorten", status: Ok, headers: {"Cache-Control": "private", "Content-Type": "application/json; charset=utf-8", "Server": "Microsoft-IIS/8.0", "X-AspNetMvc-Version": "5.2", "X-AspNet-Version": "4.0.30319", "X-Powered-By": "ASP.NET", "Date": "Thu, 15 Feb 2018 10:31:00 GMT", "Content-Length": "159"} })
Parsing result: "{\r\n  \"success\": false,\r\n  \"message\": \"This URL is blacklisted: Nah, I don\'t want to do that.\",\r\n  \"shortUrl\": null,\r\n  \"longUrl\": \"http://stackoverflow.com\"\r\n}"
```

**Comment by arshubham** [comment]
Sorry I didn't realize I was make changes here. I will revert them. I'm new with git.

**Comment by iddm** [comment]
@arshubham no problem :)

**Comment by iddm** [comment]
Found that. The `reqwest` sends itself as a `user-agent` header value, the service detects that and refuses to make a url. We need to fake the `user-agent`. The author of this service should really have made an API terms, so we would know he does not want us using his service instead of making it public and usable for everyone and then restricting the usage.

**Comment by iddm** [comment]
@arshubham I pushed new commit on top of the `master` branch. Could you rebase please?

**Comment by iddm** [comment]
I knew it! There will be error caused by me: I forgot to format the source code appropriately. I push one more commit with format fixes, so you need to rebase again :)

**Pull request merged**
