### PR TITLE
Add provider for BitURL

### PR DESCRIPTION
**Pull request by TimothyYe**
Add provider for [https://biturl.top](https://biturl.top)

All the test cases are passed.

### CODE REVIEW

**Review by iddm — APPROVED** [review]
Thanks!

**Comment by iddm** [comment]
Does this service has any use restrictions? Rate limits, agreements, anything?

**Comment by TimothyYe** [comment]
No, this service is maintained by me. There aren't any restrictions.

**Comment by iddm** [comment]
Good to know!

**Pull request merged**
